name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ !contains(github.event.pull_request.title, '[no-ci]') }}
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Format
        run: pnpm run test:fmt

      - name: Lint
        run: pnpm run test:lint

      - name: Type Check
        run: pnpm run test:tsc
