name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ !contains(github.event.pull_request.title, '[no-ci]') }}
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Format
        run: pnpm run test:fmt

      - name: Lint
        run: pnpm run test:lint

      - name: Type Check
        run: pnpm run test:tsc

      - name: Build
        run: pnpm build

      - name: Sync KV themes
        run: pnpm sync:themes:local
        env:
          SYNC_LIMIT: 3
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_KV_READ }}
          CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Install E2E Browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E tests
        run: DEBUG=pw:browser,pw:api,pw:webserver pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
