name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ !contains(github.event.pull_request.title, '[no-ci]') }}
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm test:lint

      - name: Type Check
        run: pnpm test:tsc

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Init DB & Seed
        run: pnpm db:seed

      - name: Install E2E Browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E tests
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: DEBUG=pw:browser,pw:api,pw:webserver pnpm exec playwright test
        env:
          NODE_ENV: development
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          VITE_POSTHOG_API_KEY: ${{ secrets.VITE_POSTHOG_API_KEY }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
