name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: ${{ !contains(github.event.pull_request.title, '[no-ci]') }}
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm test:lint

      - name: Type Check
        run: pnpm test:tsc

      - name: Build
        run: pnpm build

      # TODO - init d1 db using a static file (same can be used for init local dev)
      # - name: Sync KV themes
      #   run: pnpm sync:themes --limit 3
      #   env:
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_KV_READ }}
      #     CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
      #     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # - name: Install E2E Browsers
      #   run: pnpm exec playwright install --with-deps

      # - name: E2E tests
      #   run: DEBUG=pw:browser,pw:api,pw:webserver pnpm exec playwright test

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
